import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

// Only the generated CommonJS loader is adapted. The official Wasm stays byte-identical.
const ROOT = new URL('../', import.meta.url);
const SOURCE = new URL('node_modules/@visioncortex/vtracer/pkg/', ROOT);
const DESTINATION = new URL('src/js/vendor/vtracer/', ROOT);
const HASHES = {
  'vtracer_wasm.js': 'e1855e9bb29d785344f672abdc692ca90ffa7ed863b9186b51c4e95a2a7dc17d',
  'vtracer_wasm_bg.wasm': '63716b70497b7468ef97545b50f5f34b8bbb7acde2d7b00deb4eb40781446d45',
};

await mkdir(DESTINATION, { recursive: true });
for (const [name, expected] of Object.entries(HASHES)) {
  const bytes = await readFile(new URL(name, SOURCE));
  if (createHash('sha256').update(bytes).digest('hex') !== expected) {
    throw new Error(`Unexpected vtracer artifact: ${name}. Review the adapter before upgrading.`);
  }
}
let source = await readFile(new URL('vtracer_wasm.js', SOURCE), 'utf8');
source = source.replace('exports.vectorize_bytes = vectorize_bytes;', 'export { vectorize_bytes };');
source = source.replace('exports.vectorize_rgba = vectorize_rgba;', 'export { vectorize_rgba };');
const boundary = source.indexOf('const wasmPath =');
if (boundary < 0) throw new Error('The upstream Wasm loader has changed.');
source = '// Generated by scripts/prepare-vtracer.mjs. See THIRD_PARTY_NOTICES.md.\n'
  + source.slice(0, boundary) + `let wasm;
export async function initialize(url) {
    if (wasm) return;
    const response = await fetch(url);
    if (!response.ok) throw new Error('Wasm could not be loaded: ' + response.status);
    const { instance } = await WebAssembly.instantiate(await response.arrayBuffer(), __wbg_get_imports());
    wasm = instance.exports;
    wasm.__wbindgen_start();
}
`;
await writeFile(new URL('vtracer_wasm.js', DESTINATION), source);
await copyFile(new URL('vtracer_wasm_bg.wasm', SOURCE), new URL('vtracer_wasm_bg.wasm', DESTINATION));
process.stdout.write(`Prepared browser Wasm in ${fileURLToPath(DESTINATION)}\n`);
